name: Azure Static Web Apps CI/CD


pr:
  branches:
    include:
      - main
      
trigger:
  branches:
    include:
      - main

jobs:
- job: install_nodejs
  displayName: Install Node.js
  pool:
    vmImage: ubuntu-latest
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
      versionSource: 'spec'
    displayName: 'Install Node.js'
    
- job: npm_install
  displayName: npm installation
  dependsOn: install_nodejs
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install @angular/cli -g'
      workingDir: '$(Build.SourcesDirectory)'

- job: npm_custom
  displayName: npm custom
  dependsOn: npm_install
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build app-one @angular/cli -g'  
      workingDir: '$(Build.SourcesDirectory)/app-one/src/app'
      
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  dependsOn: npm_custom
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
 
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-red-bush-06aba0f0f-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_RED_BUSH_06ABA0F0F)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "dist/app-one" # Built app content directory - optional
###### End of Repository/Build Configurations ######